### ISSUE TITLE
2.0-alpha1: FileNotFoundError: ${HOME}/.config/fedcloud/logging.conf doesn't exist

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#187]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0-alpha1

### Steps to reproduce

Check out the code repository in the `2.0-alpha1` branch and run

```bash
fedcloud
```

### Expected behavior

The help text should be printed out.

### Actual behavior

```bash
 fedcloud --help
Traceback (most recent call last):
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/bin/fedcloud", line 6, in <module>
    from fedcloudclient.cli import cli
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/cli.py", line 7, in <module>
    from fedcloudclient.checkin import token
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/checkin.py", line 15, in <module>
    from fedcloudclient.decorators import (
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/decorators.py", line 14, in <module>
    from fedcloudclient.locker_auth import LockerToken
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/locker_auth.py", line 8, in <module>
    from fedcloudclient.logger import log_and_raise
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/logger.py", line 38, in <module>
    init_logger()
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/site-packages/fedcloudclient/logger.py", line 21, in init_logger
    logging.config.fileConfig(
  File "/tmp/tmp.PhAbWjrhhn/conda-install/envs/fedcloudclient/lib/python3.12/logging/config.py", line 66, in fileConfig
    raise FileNotFoundError(f"{fname} doesn't exist")
FileNotFoundError: /home/sebastian/.config/fedcloud/logging.conf doesn't exist

```

### Affected runtime and version

python@3.12

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by sebastian-luna-valero** [comment]
It works, thanks!
