### ISSUE TITLE
Better error checking/reporting for "fedcloud endpoint projects --site SITE" command

### ISSUE THREAD

**Issue by tdviet** [tdviet/fedcloudclient#50]
Currently, if the user doesn't have access to any project on the site, it will report this runtime error:

```
Traceback (most recent call last):
  File "/usr/local/bin/fedcloud", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/decorators.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/decorators.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/decorators.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/endpoint.py", line 251, in projects
    project_list = get_projects_from_sites(access_token, site)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/endpoint.py", line 168, in get_projects_from_sites
    unscoped_token, _ = get_unscoped_token(os_auth_url, access_token)
  File "/usr/local/lib/python3.9/site-packages/fedcloudclient/endpoint.py", line 112, in get_unscoped_token
    raise RuntimeError("Unable to get an scoped token")
RuntimeError: Unable to get an scoped token
```

The error message is confusing, should be checked and interpreted in a better way.

**Comment by tdviet** [comment]
Solved. https://github.com/tdviet/fedcloudclient/commit/b70f94dd5566a8a5e8b6598f0ec0531c1f687a40
