### ISSUE TITLE
Crashing sub-command: fedcloud site show

### ISSUE THREAD

**Issue by sustr4** [tdviet/fedcloudclient#71]
I am working with `fedcloud` client version `1.2.6` but I don't see any mention of a fix in the `CHANGELOG` so perhaps this is worth reporting. I have installed with `pip`.

I have downloaded site configurations with `fedcloud site save-config` and have not modified any of them. The sub-command `fedcloud site show` always crashes for me. I have tried with multiple sites, it always ends with:

```
$ fedcloud site show --site IISAS-FedCloud
Traceback (most recent call last):
  File "/home/sustr4/.local/bin/fedcloud", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sustr4/.local/lib/python3.7/site-packages/fedcloudclient/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/home/sustr4/.local/lib/python3.7/site-packages/fedcloudclient/sites.py", line 246, in show
    print(yaml.dump(site_info, sort_keys=True))
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

Other sub-commands I have tried seem to work properly, including `fedcloud site show-project-id --site...` or `fedcloud openstack --site ...`

**Comment by tdviet** [comment]
Hi Zdenek, could you check the current version of PyYAML library and try to upgrade it?
```
pip3 show -v pyyaml
pip3 install -U pyyaml
```

**Comment by sustr4** [comment]
Hi, Viet, good tip. The version I had was `3.13`, upgrade took it to `5.4.1` and it works now.

**Comment by tdviet** [comment]
TODO: add minimal version of PyYAML to requirements.txt

**Comment by tdviet** [comment]
Fixed.
https://github.com/tdviet/fedcloudclient/commit/2e0f7c2fc8210a82986a9abf89c8c6235843bf5e
